Remove dangling /rust directory
johndoe31415/labwork-docker pull request #17
Opened 2024-10-30 22:56 UTC by johndoe31415

We need the directory /rust only during container provisioning, after which it becomes obsolete. Remove it after dependencies have been vendored in.

2024-10-30 22:58 UTC, johndoe31415 commented
@PlexSheep I've overlooked this, I find `/rust` not a nice place. If we need it, I'd like to change it to `/opt/rust`, otherwise (as this PR proposes) I just remove it after having vendored in dependencies (I'm assuming they're stored in `~/.cache` somewhere). Does this work for you or would it be a breaking change?

2024-10-30 23:52 UTC, PlexSheep requested changes
As you implement it here, this will download the dependencies only to remove them all again before we can do anything again.

Do not remove the rust directory. Moving it to something like `/opt` makes sense if you want to follow the conventional paths more closely.

2024-10-30 23:52 UTC, PlexSheep commented on docker/Dockerfile
> +RUN cd /tmp/rust && cargo vendor && rm -fr /tmp/rust
This won't work. cargo vendor downloads the source codes of the specified crates into the cwd, but you are deleting it immediately afterward. Removing `/tmp/rust` undos the vendoring.

2024-10-30 23:52 UTC, PlexSheep commented on docker/Dockerfile
> +COPY rust /tmp/rust
This will break some build scripts that relied on the old path, but they can be fixed easily.

2024-10-30 23:54 UTC, PlexSheep commented
Caching might be possible somehow, I will look into the details of that tomorrow, but i don't know how reliable that would be.

2024-10-31 00:01 UTC, PlexSheep commented on docker/Dockerfile
> +RUN cd /tmp/rust && cargo vendor && rm -fr /tmp/rust
To clarify: Currently, our projects compile all the dependencies. In the current configuration, no caching happens before our executables are compiled.

2024-10-31 06:51 UTC, johndoe31415 commented
> As you implement it here, this will download the dependencies only to remove them all again before we can do anything again. **This will break our rust dependencies without fix.**
> 
> Do not remove the rust directory. Moving it to something like `/opt` makes sense if you want to follow the conventional paths more closely.

Right, let's postpone this then. I'll do this in December, so you won't have to change your repositories. Thanks for your feedback!

2025-10-21 10:12 UTC, closed without merging